// Automatically generated by astro-icon
// 8a6622874ed4867db1db1c4a61bc331e6dac548e052c49a87255104913085268

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "book"
		| "box"
		| "calendar"
		| "clock"
		| "facebook"
		| "file-text"
		| "github"
		| "home"
		| "link"
		| "linkedin"
		| "map-pin"
		| "menu"
		| "moon"
		| "rss"
		| "search"
		| "share"
		| "sun"
		| "tag"
		| "twitter"
		| "user"
		| "wechat"
		| "x";
}